/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import javax.swing.*;
import Clases.*;
import Clases.Operaciones;

import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author juanmilano
 */
@SuppressWarnings("serial")
public class ListaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ListaPedidos
     */
    
    
    public ListaPedidos() {
        initComponents();
        setLocationRelativeTo(null);
       //Invocamos el mÃ©todo privado para llenar la lista
    }
    
    
        private void Llenar_Lista_Pedidos(){
        
        //Declaramos un Objeto de Tipo Operaciones
        Operaciones objOperaciones = new Operaciones();
        
        ArrayList <LicenciaEspecial> objLicenciaEspecial;
        ArrayList <Vacaciones> objVacaciones;

        
        objLicenciaEspecial = objOperaciones.Obtener_Lista_Licencia ();
        objVacaciones = objOperaciones.Obtener_Lista_Vacaciones();

        
        //Declaramos un Objeto DefaultTableModel para llenar la Tabla 
        DefaultTableModel modelo = (DefaultTableModel)tablePedidos.getModel();
        
        //Recorremos los Elementos del ArrayList para agregarlos a la Tabla a traves del DefaultTabelModel
        for (LicenciaEspecial elemento : objLicenciaEspecial){
            //Declaramos un Arreglo para almanecar los datos de cada empleado que estan en el ArrayList
            Object[] rowData = {elemento.dniEmpleado(),
                           elemento.getCantDias(),
                           elemento.getFechaInicio(),
                           elemento.getFechaFin(),
                           elemento.getEstadoDeLicencia(),
                           elemento.getMotivoDeLicencia(),
                          };
            		   
	    modelo.addRow(rowData);
        }
    
            
    
        for (Vacaciones elemento : objVacaciones){
            //Declaramos un Arreglo para almanecar los datos de cada empleado que estan en el ArrayList
            Object[] rowData = {elemento.dniEmpleado(),
                           elemento.getCantDias(),
                           elemento.getFechaInicio(),
                           elemento.getFechaFin(),
                           elemento.getEstadoDeLicencia(),
                           elemento.periodoVacacion(),
                          };
            		   
	    modelo.addRow(rowData);
        }
    
            
    } 
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pedidos = new javax.swing.JScrollPane();
        tablePedidos = new JTable();
        jLabel1 = new JLabel();
        jButton2 = new JButton();
        jButton3 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePedidos.setModel(new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Dni Empleado", "Cantidad Dias", "Fecha Inicio", "Fecha Fin", "Estado", "Motivo"
            }
        ));
        Llenar_Lista_Pedidos();
        Pedidos.setViewportView(tablePedidos);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Pedidos");
        jLabel1.setToolTipText("");

        jButton2.setText("Volver al Menú");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        JButton btnEliminarPedido = new JButton();
        btnEliminarPedido.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		if (tablePedidos.getRowCount()> 0){
                    
                    if (tablePedidos.getSelectedRow() != -1){
                        
                        if (JOptionPane.showConfirmDialog (null, "Desea eliminar este Pedido?", "Advertencia", 
                                JOptionPane.YES_NO_OPTION)== JOptionPane.NO_OPTION)
                            return;
                        
                        //Elimina el Empleado de la Lista
                        //Declara un Objeto del Tipo DefaultTableModel
                        DefaultTableModel modelo = (DefaultTableModel) tablePedidos.getModel();
                        modelo.removeRow(tablePedidos.getSelectedRow());
                        
                    }else{
                        JOptionPane.showMessageDialog(null,"Debe seleccionar un Pedido de la Lista" ,
                                    "Error",JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                   JOptionPane.showMessageDialog(null,"No existen Pedidos en la Lista" ,
                                    "Error",JOptionPane.ERROR_MESSAGE); 
                }
        	}
        });
        btnEliminarPedido.setText("Eliminar Pedido");

        GroupLayout layout = new GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
        					.addGap(391))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(btnEliminarPedido, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        					.addGap(33)
        					.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
        					.addGap(79))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(Pedidos, GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        					.addContainerGap())))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(13)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Pedidos, GroupLayout.PREFERRED_SIZE, 397, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton3)
        				.addComponent(jButton2)
        				.addComponent(btnEliminarPedido))
        			.addGap(24))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Pedidos.setVisible(false);
       this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           if (JOptionPane.showConfirmDialog(null,"¿Está seguro que desea salir?" ,"Lista de Pedidos",
                  JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION)
           System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane Pedidos;
    private JButton jButton2;
    private JButton jButton3;
    private JLabel jLabel1;
    private JTable tablePedidos;
}
