/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

/**
 *
 * @author juanmilano
 */
@SuppressWarnings("serial")
public class MenuPrincipal extends JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloHome = new JLabel();
        cargarLicencia = new JButton();
        cargarVacaciones = new JButton();
        listadoPedidos = new JButton();
        botonSalir = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        tituloHome.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tituloHome.setText("Gestión de Recursos Humanos");

        cargarLicencia.setText("Cargar Licencia");
        cargarLicencia.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cargarLicenciaActionPerformed(evt);
            }
        });

        cargarVacaciones.setText("Cargar Vacaciones");
        cargarVacaciones.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cargarVacacionesActionPerformed(evt);
            }
        });

        listadoPedidos.setText("Ver mis Pedidos");
        listadoPedidos.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                listadoPedidosActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGap(115, 115, 115)
            .addComponent(tituloHome, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
            .addGap(142, 142, 142)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
            .addComponent(cargarLicencia, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cargarVacaciones, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listadoPedidos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonSalir, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(tituloHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(cargarLicencia)
            .addGap(18, 18, 18)
            .addComponent(cargarVacaciones)
            .addGap(18, 18, 18)
            .addComponent(listadoPedidos)
            .addGap(18, 18, 18)
            .addComponent(botonSalir)
            .addContainerGap(157, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarLicenciaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cargarLicenciaActionPerformed
        CargarLicencia CargarLicencia = new CargarLicencia();
        CargarLicencia.setVisible(true); 
    }//GEN-LAST:event_cargarLicenciaActionPerformed

    private void cargarVacacionesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cargarVacacionesActionPerformed
        CargarVacaciones CargarVacaciones = new CargarVacaciones();
        CargarVacaciones.setVisible(true); 
    }//GEN-LAST:event_cargarVacacionesActionPerformed

    private void listadoPedidosActionPerformed(ActionEvent evt) {//GEN-FIRST:event_listadoPedidosActionPerformed
        ListaPedidos ListaPedidos = new ListaPedidos();
        ListaPedidos.setVisible(true); 
    }//GEN-LAST:event_listadoPedidosActionPerformed

    private void botonSalirActionPerformed(ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
             if (JOptionPane.showConfirmDialog(null,"¿Está seguro que desea salir?" ,"Gestión de RRHH",
                    JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION)
           System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton botonSalir;
    private JButton cargarLicencia;
    private JButton cargarVacaciones;
    private JButton listadoPedidos;
    private JLabel tituloHome;
    // End of variables declaration//GEN-END:variables
}
